### ISSUE TITLE
dogma release contains a bunch of unncessary files

### ISSUE THREAD

**Issue by staabm** [paranoiq/dogma-dev#1]
when installing `sqlftw/sqlftw` we automatically get `dogma` as a transitive dependency.

I just stumbled over the dogma folder and was suprised that it contains so many non-release files

<img width="311" alt="grafik" src="https://user-images.githubusercontent.com/120441/225751307-6465bbb7-b5e8-4215-a2ab-f5f65acfe745.png">

I would not expect 
- tests
- doc
- build
folder in a release

**Comment by paranoiq** [comment]
this is on wrong repo. you probably ment https://github.com/paranoiq/dogma ^_^ (fixed there)

**Comment by staabm** [comment]
You are right. I realized it later on but figured you would it out ;-). 

Thx for fixing
